server:
  port: 8083
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pfe_base?serverTimezone=UTC
    username: root
    password: sa3douune
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update